name: Test pywrstat

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox

  version_bump:
    if: ${{ github.event.pull_request.base.sha }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check version bump
        run: |
          git fetch origin master ${{ github.event.pull_request.base.sha }}
          bin/check-version-bump.sh ${{ github.event.pull_request.base.sha }}  

  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
          pre-build-command: "pip install -r requirements.txt && pip install furo==2022.4.7 enum-tools[sphinx] && python setup.py build install"
          build-command: "sphinx-build -b html source/ build/"
